---
name: POE-Component-WWW-Pastebin-Bot-Pastebot-Create
version: 0.002
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: non-blocking POE wrapper around WWW::Pastebin::Bot::Pastebot::Create
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Component::NonBlockingWrapper::Base: 0.002
  WWW::Pastebin::Bot::Pastebot::Create: 0.001
build_requires:
  Test::More: 0
provides:
  POE::Component::WWW::Pastebin::Bot::Pastebot::Create:
    file: lib/POE/Component/WWW/Pastebin/Bot/Pastebot/Create.pm
    version: 0.002
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
